export const PAGINATION = {
  DEFAULT_LIMIT: 25,
  MAX_LIMIT: 100,
  PORTAL_DEFAULT_LIMIT: 25,
  ADMIN_DEFAULT_LIMIT: 50,
} as const;

export const RATE_LIMITS = {
  LEAD_CAPTURE_PER_IP: 10,
  LEAD_CAPTURE_WINDOW_MINUTES: 10,
  ADMIN_QUERIES_PER_MINUTE: 100,
  ADMIN_EXPORTS_PER_HOUR: 10,
  PORTAL_QUERIES_PER_MINUTE: 60,
} as const;

export const CACHE_TTL = {
  SSM_PARAMETERS: 60, // seconds
  FEATURE_FLAGS: 60,
  ANALYTICS_RESULTS: 300, // 5 minutes
  RATE_LIMIT_WINDOW: 600, // 10 minutes
} as const;

export const DATA_RETENTION = {
  LEADS_DAYS: 90,
  AUDIT_LOGS_DAYS: 365,
  EXPORTS_HOURS: 24,
  NOTIFICATIONS_DAYS: 30,
  WEBHOOK_DELIVERIES_DAYS: 7,
} as const;
